### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [12]:
ar1=np.zeros(10)
print(f"An array of 10 zeros:\n{ar1}")
ar2=np.ones(10)
print(f"An array of 10 ones:\n{ar2}")
ar3=np.full((10),5,dtype=float)
print(f"An array of 10 fives:\n{ar3}")

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [17]:
ar4=np.arange(30,71)
print(f"Array of the integers from 30 to70\n{ar4}")

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [19]:
ar5=np.arange(10,50,2)
print(f"Array of all the even integers from 10 to 50\n{ar5}")

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [27]:
ar6=np.identity(3)

print(f"3x3 matrix:\n{ar6}")

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [32]:
ar7=np.random.random()
print(ar7)

0.8143231701148894


In [33]:
## sample output

###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [9]:
np.random.randn(15)

array([ 0.0924241 ,  0.05314322,  1.29589888, -0.72949035, -1.08669223,
        0.635323  ,  1.07381069, -0.29758378,  1.87130185,  0.02565269,
        1.07249076, -0.4750226 , -0.20987475, -0.49750362, -1.11232032])

In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [7]:
ar8=np.arange(10,22).reshape(3,4)
print("Original array:\n",ar8)
print("Each element of the array is:")
for i in np.nditer(ar8):
    print(i,end=' ')

Original array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [127]:
vec1=np.array([1 ,8 ,3 ,5])
print("Vectoe-1\n",vec1)
vec2=np.array([10  ,1  ,4 ,10])
print("Vector-2\n",vec2)
c=np.multiply(vec1,vec2)
print("Multiply the values of two said vectors:\n",c)

Vectoe-1
 [1 8 3 5]
Vector-2
 [10  1  4 10]
Multiply the values of two said vectors:
 [10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [74]:
ar9=np.array([12 ,13, 14 ,15 ,16 ,17 ,18 ,19 ,20 ,21 ,22 ,23 ,24 ,25 ,26 ,27 ,28 ,29 ,30 ,31 ,32 ,33 ,34 ,35
 ,36 ,37])
print("Original array:\n",ar9)
c=np.flip(ar9)
print("Reverse array:\n",c)

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [1]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [76]:
ar10=np.diag([1,2,3,4,5])
print(ar10)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [102]:
ar11=np.array([[0,1],[2,3]])
print("Original array:\n",ar11)
sum_ele=np.sum(ar11)
print("Sum of all elements:\n",sum_ele)
sum_col=np.sum(ar11,axis=0)
print("Sum of each column:\n",sum_col)
sum_row=np.sum(ar11,axis=1)
print("Sum of each column:\n",sum_row)


Original array:
 [[0 1]
 [2 3]]
Sum of all elements:
 6
Sum of each column:
 [2 4]
Sum of each column:
 [1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [82]:
a1=np.array([4,5])
print("Original vectors:")
print(a1)
a2=np.array([7,10])
print(a2)
print("Inner product of said vectors:")
c1=np.inner(a1,a2)
print(c1)

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
