1) Write a program to create a 5 dimensional array with all zeros and ones

In [2]:
import numpy as np

In [8]:
array_1=np.array([np.zeros(5)],ndmin=5,dtype=int)
array_2=np.array([np.ones(5)],ndmin=5,dtype=int)

In [9]:
array_1

array([[[[[0, 0, 0, 0, 0]]]]])

In [10]:
array_2

array([[[[[1, 1, 1, 1, 1]]]]])

2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which

    create a new array of shape (3,10)

In [35]:
arr1=np.zeros(10,dtype=int)
arr2=np.ones(10,dtype=int)
arr3=np.full(10,5)
np.vstack([arr1,arr2,arr3])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [37]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

4) Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to
    0,1,2,3,4,5,6,7,8,9,

In [39]:
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])


5)Write a program to create a 4x4 array. Create an array from below array by swapping first and
last, second and third columns.

In [52]:
arr3=np.arange(1,17).reshape(4,4)

In [53]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
arr3[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

6) Write a program to reverse an array (the first element becomes the last).
    Given array:


In [65]:
ar3=np.arange(12,28)
np.flip(ar3)

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5
    from an array of shape 10,10 .Elements range from 1 to 100


In [81]:
arr1=np.arange(1,101)
print(arr1)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [82]:
in30_80=arr1[(arr1>30) & (arr1<80) & (arr1%5==0)]

In [84]:
print(f"the elements greater than 30 and 80 and multiples of 5 \n{in30_80}")

the elements greater than 30 and 80 and multiples of 5 
[35 40 45 50 55 60 65 70 75]


8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [97]:
oner=np.ones(9).reshape(3,3)
oner[1][1]=0
print(oner)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


9) Write a program to create a checkerboard pattern .Don't use default array function
  Checkerboard pattern:


In [150]:
c=np.eye(2,dtype=int)[::-1]
d=np.tile(c,(4,4))
print("Checkerboard pattern:")
print(d)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
10) Write a program to find common values between two arrays.
Expected Output:

In [151]:
arr2 = np.array([10, 20 ,40 ,60])
arr3 =np.array([10, 30, 40,50])

In [152]:
c=np.intersect1d(arr2,arr3)

In [154]:
print("common values between two arrays:\n",c)

common values between two arrays:
 [10 40]


11) Write a program to create an array 2d array and then reshape into 1d array


In [167]:
d2=np.arange(1,10).reshape(3,3)
print("2D array:\n",d2)
print("Reshape into 1D array:\n",d2.reshape(-1))

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshape into 1D array:
 [1 2 3 4 5 6 7 8 9]


12) Write a user defined function for creating a 1 or 2d array from scratch without using array
    functions


In [196]:
def cre_ar(col,num=0):
    array = []
    for i in range(col):
        col = num
        
        array.append(col)
    return array
one1D = cre_ar(col=int(input("enter number of elements: ")),num=int(input("enter the number:")))
print("1D Array:")
print(one1D)

enter number of elements: 3
enter the number:3
1D Array:
[3, 3, 3]


In [195]:
def cre_ar(rows,colums,num):
    for i in range(rows):
        array=[]
        row = [num] * colums
        array.append(row)
        return array      
            
two2D = cre_ar(rows=int(input("enter number of cloumsn")),
               colums=int(input("enter number of columns")),
               num=int(input("enter the number")))
print("2D Array")
for row in two2D:
    print(row)
    print(two2D)


enter number of cloumsn2
enter number of columns2
enter the number3

2D Array
[3, 3]
[[3, 3]]
