### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [2]:
import numpy as np

In [28]:
arr1=np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])
print("Original array:\n",arr1)
print("Find the missing data of the said array:\n",np.isnan(arr1))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [32]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)
np.array_equal(a,b)

True

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [13]:
a=np.array([[ 0 , 1 , 2,  3], [ 4,  5 , 6 , 7], [ 8 , 9 ,10 ,11], [12 ,13 ,14 ,15]])

print("Original array:\n",a)
print("New array after swapping first and last rows of the aray:\n",a[::-1,:])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first and last rows of the aray:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [5]:
lst=[1,2,3,5,6,7,8,5,3,12,3,6,87]
print("list to arrays")
np.array(lst)

list to arrays


array([ 1,  2,  3,  5,  6,  7,  8,  5,  3, 12,  3,  6, 87])

In [6]:
tup=[3,5,56,5,4,4,56,7,5,4,4,4,5]
print("tupple to array")
np.array(tup)

tupple to array


array([ 3,  5, 56,  5,  4,  4, 56,  7,  5,  4,  4,  4,  5])

###### 5. Write a NumPy program to find common values between two arrays.

In [53]:
a=np.arange(1,10).reshape(3,3)
print("array1\n",a)
b=np.arange(1,19,2).reshape(3,3)
print("array2\n",b)
print("common values between two arrays:\n",np.intersect1d(a,b))

array1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
common values between two arrays:
 [1 3 5 7 9]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [60]:
ar1=np.array([[1,2],[3,4],[5,6]])
print("Reshape 3x2:\n",ar1)
print("Reshape 2x3:\n",ar1.reshape(2,3))

Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [75]:
oa=np.array([10, 10, 20, 10, 20, 20, 20 ,30 ,30 ,50 ,40 ,40])
print(f"Original array:\n{oa}")
unique,frequency=np.unique(oa,return_counts=True)
c=np.array([unique,frequency])
print(f"Frequency of unique values of the said array:\n{c}")

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [79]:
p=np.array([[0,0,0],[1,2,3],[4,5,6]])
print("Originak arrays:\n","Array-1\n",p)
q=([10,11,12])
print("Array-2\n",q)
print("New Array:\n",p+q)

Originak arrays:
 Array-1
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
 [10, 11, 12]
New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [86]:
ar_1=np.arange(0,16).reshape(4,4)
print(f"Original array:\n{ar_1}")
print("Extracted data: second row")
print(ar_1[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: second row
[4 5 6 7]


In [20]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [17]:
sp=np.arange(0,16).reshape(4,4)
print("Original array:")
print(sp)
print("Extracted data: Third and fourth elements of the first and second rows :\n",sp[:2,2:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows :
 [[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code

In [50]:
import numpy as np
yest= np.datetime64(today)- np.timedelta64(1)
print("Yestraday:",yest)
today= np.datetime64(today)
print("Today:",today)
tom= np.datetime64(today, 'D')+ np.timedelta64(1)
print("Tomorrow:",tom)

Yestraday: 2023-08-28
Today: 2023-08-29
Tomorrow: 2023-08-30


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [48]:
import numpy as np
print("First Monday in May 2017:\n",np.busday_offset('2017-05',0, weekmask='Mon'))

First Monday in May 2017:
 2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
