# 1

In [397]:
import numpy as np

In [398]:
b=np.genfromtxt(r"C:\Users\vinay\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [399]:
total_bill=b[:,1]
tip=b[:,2]
sex=b[:,3]
smoker=b[:,4]
day=b[:,5]
time=b[:,6]
size=b[:,7]
mind=np.where(sex==1)
male=sex.take(mind)
find=np.where(sex==0)
female=sex.take(find)

#### 1-what is the total bill value

In [400]:
val_totl=np.sum(total_bill)
print("Total bill value:",val_totl)

Total bill value: 4827.77


#### 2- what is the total tip value

In [401]:
val_tip=np.sum(tip)
print("total tip:",val_tip)

total tip: 731.5799999999999


#### 3- count how many sun,sat thu,fri are there 

In [459]:
sind=np.where(day==0)
sunday=day.take(sind)
stind=np.where(day==1)
sat=day.take(stind)
tind=np.where(day==2)
thu=day.take(tind)
find=np.where(day==3)
fri=day.take(find)
print("Number of sunday:",sunday.size)
print("Number of saturday:",sat.size)
print("Number of thursday:",thu.size)
print("Number of friday:",fri.size)

Number of sunday: 87
Number of saturday: 76
Number of thursday: 62
Number of friday: 19


#### 4-how many smokers are there 

In [402]:
print("number of smokers:",np.count_nonzero(smoker))

number of smokers: 93


#### 5- what is the avg tip given by female and male

In [447]:
avg_tipf=tip.take(find)
avg_tipm=tip.take(mind)
print("average tip given by male:",np.average(avg_tipm))
print("average tip given by female:",np.average(avg_tipf))

average tip given by male: 3.0896178343949043
average tip given by female: 2.8334482758620685


### 6- how much amount have been spent by female and male

In [453]:
x1=np.sum(tip.take(mind))
x2=np.sum(tip.take(find))

print("total amount spent by male:",np.sum(total_bill.take(mind)+x1))
print("total amount spend by female:",np.sum(total_bill.take(find)+x2))

total amount spent by male: 79412.81
total amount spend by female: 23017.32


#### 7-what is the min and mix tip given

In [405]:
max_tip=np.max(tip)
min_tip=np.min(tip)
print("max tip:",max_tip)
print("min tip:",min_tip)

max tip: 10.0
min tip: 1.0


### 8- how many male and females are going for dinner and lunch

In [467]:
male_dl=time.take(mind)
female_dl=time.take(find)
print("number males going for lunch and dinner:",male_dl.size)
print("number females going for lunch and dinner:",female_dl.size)

number males going for lunch and dinner: 157
number females going for lunch and dinner: 19


#### 9- find out the avg size

In [407]:
avg_size=np.average(size)
print("average size:",avg_size)

average size: 2.569672131147541


#### 10- how many female smokers are there and male smokers are there

In [429]:
number1=np.where(smoker==1)
num_smokers=sex.take(number1)
ms_ind=np.where(num_smokers==1)
male_smokers=sex.take(ms_ind)
fs_ind=np.where(num_smokers==0)
female_smokers=sex.take(fs_ind)
print("number of male smokers:",np.count_nonzero(male_smokers))
print("number of female smokers:",female.size)

number of male smokers: 46
number of female smokers: 87


# 2------------------------------------------------------------------------------------->

In [280]:
a=np.genfromtxt(r"C:\Users\vinay\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [328]:
length=a[:,0]
diameter=a[:,1]
hight=a[:,2]
weight=a[:,3]
sw=a[:,4]
vw=a[:,5]
shw=a[:,6]
age=a[:,7]

#### 1-what is the max and min length

In [331]:
m=np.max(length)
m1=np.min(length)
print(f"max: {m}")
print("min:",m1)

max: 7.58349125
min: 0.0


#### 2-find out the diff b/w max and min lenght

In [332]:
print("difference betweeen max and min")
c=np.subtract(m,m1)
print(c)

difference betweeen max and min
7.58349125


#### 3-Find colomnwise average

In [294]:
print("column wise average:\n",np.average(a,axis=0))


column wise average:
 [ 1.31244808  1.02032036  0.34602787 23.12343631  9.98937025  4.99318096
  6.63422915  9.950615  ]


#### 4-Find out all the age whose hight is >0.4

In [335]:
h0=np.where(hight>0.4)
print("Age whose hight greater then 0.4")
age.take(h0)

Age whose hight greater then 0.4


array([[11., 14., 13., ..., 11., 11., 11.]])

#### 5- what is the avg hight and weight of the persons who age is 10

In [343]:
avg_hw=np.where(age==10)
g=hight.take(avg_hw)
k=weight.take(avg_hw)
avg_h=np.average(g)
avg_w=np.average(k)
print("average hight persons with age is 10:",avg_h)
print("average hight persons with age is 10:",avg_w)

average hight persons with age is 10: 0.3833672856539947
average hight persons with age is 10: 28.243308450511314


#### 6- what is the total shell weight

In [248]:
print("total of shell weight:",np.sum(sw))

total of shell weight: 1997874.0496098


#### 7-how many persons belongs to each and every unique age

In [363]:
unique,counts=np.unique(age,return_counts=True)
print("persons:",np.count_nonzero(unique))
print("unique",unique)
print("counts:",counts)


persons: 28
unique [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 29.]
counts: [   46    42   625  2787  5475 12450 18276 26818 32906 30803 23457 12717
 10037  6352  4831  3191  2705  1953  1591  1206   721   296   352   110
    51    46    99    57]


#### 8-What is the diff b/w shucked weight and viscera weight

In [468]:
print("diff bw shucked and viscera weight")
print(np.subtract(sw,vw))

diff bw shucked and viscera weight
[5.9817445 3.855532  4.1106775 ... 2.9199985 5.329706  9.8372765]


In [344]:
np.setdiff1d(sw,vw)

array([ 0.1162535 ,  0.18931875,  0.25883225, ..., 42.410852  ,
       43.1762885 , 45.2741515 ])

#### 9-what is the avg hight of the persons whose age is b/w 14 and 19

In [353]:
h14_19=np.where((age>=14) & (age<=19))
avgh=hight.take(h14_19)
print("aveg of hight of persons age b/w 14-19:\n",np.average(avgh))

aveg of hight of persons age b/w 14-19:
 0.41489902051107985


#### 10-what is the avg weight if we include shucked weight , viscera weight,shell weight

In [150]:
weight=a[:,3]
print(weight)

[31.22697425 21.885814   28.25027675 ... 10.886208   33.89182725
 34.37376875]


In [354]:
tot_weight=np.sum([weight,sw,vw],axis=0)
avg_tot=np.average(tot_weight)
print("average weight:",avg_tot)

average weight: 38.10598751778014
